service: serverless-nodejs-api

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  deploymentBucket:
    name: stest-serverless-api-tong
functions:
  getMsg:
    handler: handler.api
    events:
      - http: GET /
