service: serverless-nodejs-api

custom:
  stage: ${opt:stage, 'dev'}
  # configuration: ${file(config.yml)}
  
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  # region: ${self:custom.configuration.region}
  region: ${env:AWS_REGION}
  stackName: ${self:provider.stage}-serverless-nodejs-api

functions:
  getMsg:
    handler: handler.api
    events:
      - http: GET /
    environment:
      # test_env: ${self:custom.configuration.test_env}
      test_env: ${env:test_env}
