service: serverless-nodejs-api

custom:
  stage: ${opt:stage, 'dev'}
  configuration: ${file(configurations/${self:custom.stage}.yml)}
  
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.configuration.region}

functions:
  getMsg:
    handler: handler.api
    events:
      - http: GET /
    environment:
      test_env: ${self:custom.configuration.test_env}
