service: serverless-nodejs-api

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  deploymentBucket:
    name: serverless-api-test
functions:
  getMsg:
    handler: handler.api
    events:
      - http: GET /
